ENV PORT=8080
EXPOSE 8080

ENV DATABASE_URL=postgresql://neondb_owner:npg_zHgsEUcGN21i@ep-tiny-resonance-a16yxips-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
ENV WASP_WEB_CLIENT_URL=https://onceagain-blog.netlify.app


